package com.specialeffect.utils;

import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

public class ModUtils {

	// A helper function to replace mcmod.info. Must be called with 
	// a pre-init event.
	public static void setupModInfo(FMLPreInitializationEvent event,
									String modId, String modVersion, String modName,
									String modDescription) {

		// Adding info here avoids having to maintain a mcmod.info file.
		ModMetadata m = event.getModMetadata(); 
		m.autogenerated = false;
		m.modId = modId;
		m.version = modVersion;
		m.name = modName;
		m.url = "https://github.com/kirstymcnaught/SpecialEffectMinecraftMods";
		m.description = modDescription;
		m.authorList.add("Kirsty McNaught");
		m.credits = "Written in collaboration with SpecialEffect";
	}
}
