plugins {
    id 'net.darkhax.curseforgegradle'
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
}

repositories {
    maven {
        url "https://maven.shedaniel.me/"
    }
    maven {
        url "https://maven.terraformersmc.com/"
        content {
            includeGroup "com.terraformersmc"
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    // Cloth Config for Fabric config GUI
    api("me.shedaniel.cloth:cloth-config-fabric:${cloth_config_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }
    // Mod Menu
    implementation("com.terraformersmc:modmenu:${mod_menu_version}"){
        exclude(group: "eu.pb4")
    }
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

if (System.getenv().CURSEFORGE_TOKEN) {
    def cfReleaseType = rootProject.version.toString().contains("alpha") ? "alpha" :
            rootProject.version.toString().contains("beta") ? "beta" : "release"

    task curseforge(type: net.darkhax.curseforgegradle.TaskPublishCurseForge) {
        apiToken = System.getenv().CURSEFORGE_TOKEN

        def mainFile = upload(project.curseforge_id, jar)
        mainFile.releaseType = cfReleaseType
        mainFile.addModLoader "Fabric"
        mainFile.addGameVersion rootProject.minecraft_version
        mainFile.addJavaVersion "Java ${rootProject.java_version}"
        mainFile.addEnvironment('Client')

        mainFile.displayName = "eyemine-${rootProject.minecraft_version}-fabric-${rootProject.version.toString()}"
        mainFile.changelog = rootProject.file("changes.md")
        mainFile.changelogType = 'markdown'

        mainFile.addRequirement("fabric-api", "cloth-config")
    }
}