plugins {
    // https://fabricmc.net/develop/
    id 'net.fabricmc.fabric-loom' version '1.16.1' apply false
    // https://projects.neoforged.net/neoforged/moddevgradle
    id 'net.neoforged.moddev' version '2.0.141' apply false
    id "net.darkhax.curseforgegradle" version "1.3.33" apply(false)
}
