org.gradle.jvmargs=-Xmx2048M
org.gradle.daemon=false

minecraft_version=1.20.4
java_version=17
enabled_platforms=fabric,neoforge,forge

archives_base_name=eyemine
mod_version=5.1.0
maven_group=com.specialeffect

architectury_version=11.1.17
cloth_config_version=13.0.121
mod_menu_version=9.0.0

fabric_loader_version=0.15.1
fabric_api_version=0.95.4+1.20.4

forge_version=49.0.49
neoforge_version=20.4.195