org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Project
version=7.0.0
group=com.specialeffect
java_version=25

# Common
minecraft_version=26.1.1
mod_name=EyeMine
mod_author=Kirsty McNaught, Mrbysco
mod_id=eyemine
license=GPL-3.0
credits=SpecialEffect
description=Eye gaze control for Minecraft
minecraft_version_range=[26.1, 26.2)
neo_form_version=26.1.1-1

# Fabric - https://fabricmc.net/develop/
fabric_version=0.145.4+26.1.1
fabric_loader_version=0.18.4

# NeoForge - https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.1.1.11-beta
neoforge_loader_version_range=[4,)
