org.gradle.jvmargs=-Xmx2048M
org.gradle.daemon=false

minecraft_version=1.21.1
enabled_platforms=fabric,neoforge

archives_base_name=eyemine
mod_version=6.0.2-SNAPSHOT
maven_group=com.specialeffect

architectury_version=13.0.8
cloth_config_version=15.0.140
mod_menu_version=11.0.3

fabric_loader_version=0.16.10
fabric_api_version=0.115.0+1.21.1

forge_version=52.1.0
neoforge_version=21.1.148