plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neo_form_version
    addModdingDependenciesTo(sourceSets.test)
}

configurations {
    commonJava {
        canBeConsumed = true
        canBeResolved = false
    }
    commonResources {
        canBeConsumed = true
        canBeResolved = false
    }
}

dependencies {
    compileOnly "org.spongepowered:mixin:0.8.7"
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.mockito:mockito-core:5.20.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test', Test) {
    useJUnitPlatform()
    workingDir = layout.buildDirectory.dir('test-run').get().asFile
    doFirst {
        workingDir.mkdirs()
    }
}

artifacts {
    commonJava(sourceSets.main.java.sourceDirectories.singleFile) {
        builtBy(tasks.named('classes'))
    }
    commonResources(sourceSets.main.resources.sourceDirectories.singleFile) {
        builtBy(tasks.named('classes'))
    }
}
