plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neo_form_version
}

configurations {
    commonJava {
        canBeConsumed = true
        canBeResolved = false
    }
    commonResources {
        canBeConsumed = true
        canBeResolved = false
    }
}

dependencies {
    compileOnly "org.spongepowered:mixin:0.8.7"
}

artifacts {
    commonJava(sourceSets.main.java.sourceDirectories.singleFile) {
        builtBy(tasks.named('classes'))
    }
    commonResources(sourceSets.main.resources.sourceDirectories.singleFile) {
        builtBy(tasks.named('classes'))
    }
}
