modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
issueTrackerURL="https://github.com/SpecialEffect/SpecialEffectMinecraftMods"
license="${license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="https://www.specialeffect.org.uk/eyemine"
authors="${mod_author}"
logoFile="eyemine_logo.png"
credits="${credits}"
description='''${description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"

[[mixins]]
config="eyemine-common.mixins.json"
