modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/SpecialEffect/SpecialEffectMinecraftMods"
license="GPL-3.0"

[[mods]]
modId="eyemine"
version="${version}"
displayName="EyeMine"
displayURL="https://www.specialeffect.org.uk/eyemine"
authors="Kirsty McNaught, Mrbysco"
logoFile="eyemine_logo.png"
credits = "Written in collaboration with SpecialEffect"
description='''
EyeMine by SpecialEffect allows you to play Minecraft using eye gaze.

It is designed to work alongside the EyeMine gaze-controlled keyboard. 

For questions or support, contact eyemine@specialeffect.org.uk
'''

[[dependencies.eyemine]]
	modId="neoforge"
	type="required"
	versionRange="[21.0.0-beta,)"
	ordering="NONE"
	side="CLIENT"
[[dependencies.eyemine]]
	modId="minecraft"
	type="required"
	versionRange="[1.21,1.22]"
	ordering="NONE"
	side="CLIENT"



[[dependencies.eyemine]]
modId = "architectury"
type = "required"
versionRange = "[15.0.127,)"
ordering = "AFTER"
side = "BOTH"
[[mixins]]
config = "eyemine-common.mixins.json"