plugins {
    id 'net.darkhax.curseforgegradle'
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

def accessTransformerFile = project(':common').file("src/main/resources/META-INF/accesstransformer.cfg")

neoForge {
    version = neoforge_version

    if (accessTransformerFile.exists()) {
        accessTransformers.from(accessTransformerFile)
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }

    runs {
        client {
            client()
            ideName = 'NeoForge Client'
        }

        server {
            server()
            ideName = 'NeoForge Server'
        }

        clientData {
            clientData()
            ideName = 'NeoForge Client Data'
            programArguments.addAll("--mod=${mod_id}", "--output=${file("src/generated/resources").absolutePath}", "--existing=${file("src/main/resources").absolutePath}")
        }

        serverData {
            serverData()
            ideName = 'NeoForge Server Data'
            programArguments.addAll("--mod=${mod_id}", "--output=${file("src/generated/resources").absolutePath}", "--existing=${file("src/main/resources").absolutePath}")
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

if (System.getenv().CURSEFORGE_TOKEN) {
    def cfReleaseType = rootProject.version.toString().contains("alpha") ? "alpha" :
            rootProject.version.toString().contains("beta") ? "beta" : "release"

    task curseforge(type: net.darkhax.curseforgegradle.TaskPublishCurseForge) {
        apiToken = System.getenv().CURSEFORGE_TOKEN

        def mainFile = upload(project.curseforge_id, jar)
        mainFile.releaseType = cfReleaseType
        mainFile.addModLoader "NeoForge"
        mainFile.addGameVersion rootProject.minecraft_version
        mainFile.addJavaVersion "Java ${rootProject.java_version}"
        mainFile.addEnvironment('Client')

        mainFile.displayName = "eyemine-${rootProject.minecraft_version}-neoforge-${rootProject.version.toString()}"
        mainFile.changelog = rootProject.file("changes.md")
        mainFile.changelogType = 'markdown'
    }
}
