plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

def accessTransformerFile = project(':common').file("src/main/resources/META-INF/accesstransformer.cfg")

neoForge {
    version = neoforge_version

    if (accessTransformerFile.exists()) {
        accessTransformers.from(accessTransformerFile)
    }

    runs {
        client {
            client()
            ideName = 'NeoForge Client'
        }

        server {
            server()
            ideName = 'NeoForge Server'
        }

        clientData {
            clientData()
            ideName = 'NeoForge Client Data'
            programArguments.addAll("--mod=${mod_id}", "--output=${file("src/generated/resources").absolutePath}", "--existing=${file("src/main/resources").absolutePath}")
        }

        serverData {
            serverData()
            ideName = 'NeoForge Server Data'
            programArguments.addAll("--mod=${mod_id}", "--output=${file("src/generated/resources").absolutePath}", "--existing=${file("src/main/resources").absolutePath}")
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'
