plugins {
    id "com.matthewprenger.cursegradle" version "1.4.0"
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

def accessTransformerFile = project(':common').file("src/main/resources/META-INF/accesstransformer.cfg")

neoForge {
    version = neoforge_version

    if (accessTransformerFile.exists()) {
        accessTransformers.from(accessTransformerFile)
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }

    runs {
        client {
            client()
            ideName = 'NeoForge Client'
        }

        server {
            server()
            ideName = 'NeoForge Server'
        }

        clientData {
            clientData()
            ideName = 'NeoForge Client Data'
            programArguments.addAll("--mod=${mod_id}", "--output=${file("src/generated/resources").absolutePath}", "--existing=${file("src/main/resources").absolutePath}")
        }

        serverData {
            serverData()
            ideName = 'NeoForge Server Data'
            programArguments.addAll("--mod=${mod_id}", "--output=${file("src/generated/resources").absolutePath}", "--existing=${file("src/main/resources").absolutePath}")
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

if (System.getenv("CURSEFORGE_TOKEN")) {
    def cfReleaseType = rootProject.version.toString().contains("alpha") ? "alpha" :
                        rootProject.version.toString().contains("beta") ? "beta" : "release"

    curseforge {
        apiKey = System.getenv("CURSEFORGE_TOKEN")
        project {
            id = rootProject.curseforge_id
            changelog = rootProject.file("changes.md").text
            changelogType = "markdown"
            releaseType = cfReleaseType
            addGameVersion rootProject.minecraft_version
            addGameVersion "NeoForge"
            addGameVersion "Java ${rootProject.java_version}"
            mainArtifact(tasks.named("jar").get()) {
                displayName = "eyemine-${rootProject.minecraft_version}-neoforge-${rootProject.version.toString()}"
            }
        }
        options {
            forgeGradleIntegration = false
            javaVersionAutoDetect = false
        }
    }
}
