package com.specialeffect.utils;

import java.awt.Point;

import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.ScaledResolution;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

public class ModUtils {

	// A helper function to replace mcmod.info. Must be called with 
	// a pre-init event.
	public static void setupModInfo(FMLPreInitializationEvent event,
									String modId, String modVersion, String modName,
									String modDescription) {

		// Adding info here avoids having to maintain a mcmod.info file.
		ModMetadata m = event.getModMetadata(); 
		m.autogenerated = false;
		m.modId = modId;
		m.version = modVersion;
		m.name = modName;
		m.url = "https://github.com/kirstymcnaught/SpecialEffectMinecraftMods";
		m.description = modDescription;
		m.authorList.add("Kirsty McNaught");
		m.credits = "Written in collaboration with SpecialEffect";
	}
	
	// Get the x, y point corresponding to one of 8 compass points
	// 0 = N, 1 = NE, 2 = E, etc ...
	public static Point getCompassPoint(int i) {
		Point p = new Point(0,  0);	
		i = i % 8;
		switch (i) {
		case 0:
			p.setLocation(0, +1);
			break;
		case 1:
			p.setLocation(+1, +1);
			break;
		case 2:
			p.setLocation(+1, 0);
			break;
		case 3:
			p.setLocation(+1, -1);
			break;
		case 4:
			p.setLocation(0, -1);
			break;
		case 5:
			p.setLocation(-1, -1);
			break;
		case 6:
			p.setLocation(-1, 0);
			break;
		default:
			p.setLocation(-1, +1);
			break;
		}
		return p;
	}
	
	public static Point getScaledDisplaySize(Minecraft mc) {
		Point p = new Point(0,  0);	
		
		ScaledResolution res = new ScaledResolution( mc,
				mc.displayWidth, mc.displayHeight);
		p.setLocation(res.getScaledWidth(), res.getScaledHeight());
		
		return p;
		
	}
}
