name: Preview Build

on:
  workflow_dispatch:

jobs:
  wrong-branch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This is a legacy branch with no automated build."
          echo "To run the Preview Build workflow, switch to an architectury_* branch using the branch dropdown above."
